### PR TITLE
updating lazy load to 1.9.3

### PR DESCRIPTION
**Pull request by tyler-dot-earth**

### CODE REVIEW

**Comment by sbleon** [comment]
Thanks for the PR, @tsnieman !

Can you explain why want to use a data uri instead of the `grey.gif` image? This decision will add ~180 bytes to the size of the page for each image. I'm not sure what the benefits are.

**Comment by tyler-dot-earth** [comment]
Oh woop, I meant to do this pull request from its own branch. Guess I shouldn't code half-asleep!

But the reason I did it was because 1) grey.gif wasn't loading after I updated1.9.3, and 2) it reduces the network requests, because you no longer have to load another image (since its inline). I'm not sure it's better, but I will generally like to reduce requests more than size. Again, I was going to keep that on my own branch but shouldn't have been doing this while so tired.

That being said, I'm curious to know how you feel about that change.

I'd be happy to tailor a new pull request from a branch that only includes the update if you're still not feeling this. Pardon the confusion!

**Comment by sbleon** [comment]
I'd prefer to keep grey.gif as the default behavior. It should only result
in one extra request per page, and it should be cached unless the server is
poorly configured. I'm happy to help look at the post-upgrade loading issue.

I'd love it if you could break up the PR into two. Maybe the data-uri can
be an optional feature?

Thanks again!

**Comment by tyler-dot-earth** [comment]
You're right, that's probably a better option. I'll make a new PR for the update (and look into the data-uri as a feature). Thanks for the feedback!

**Pull request closed without merging**
